export {h} from './h'
export {renderSlots} from './helpers/renderSlots'
export { getCurrentInstance } from './component' 
export { createTextVNode } from './vnode'
export { provide , inject } from './apiInject'
export { createRenderer } from './renderer'